# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-front:
    docker:
      - image: cimg/node:12.22.8
    working_directory: ~/project
    steps:
      - run: git clone https://github.com/bobonzo/circleci-spa-asmple.git

      - run: cd ./circleci-spa-asmple && npm install
      - run: cd ./circleci-spa-asmple && npm run build

      - persist_to_workspace:
              root: ./circleci-spa-asmple/dist
              paths:
                    - "*"
      - store_artifacts:
              path: ./circleci-spa-asmple/dist
              destination: /front-artifacts
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - setup_remote_docker:
              docker_layer_caching: false
      - checkout

      - attach_workspace:
              at: /tmp/circleci-spa-asmple

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test

      - run: mkdir ./src/main/resources/static && cp -R /tmp/circleci-spa-asmple/* ./src/main/resources/static
      
      - run: gradle bootBuildImage

      - run: docker images

      - run: docker tag demo:0.0.1-SNAPSHOT 246188012812.dkr.ecr.ap-northeast-1.amazonaws.com/circleci-many-repo-sample:latest

      - run: docker images

      - aws-ecr/ecr-login

      - run: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 246188012812.dkr.ecr.region.amazonaws.com

      - run: docker push 246188012812.dkr.ecr.region.amazonaws.com/circleci-many-repo-sample:latest
      
      # - aws-ecr/push-image:
      #     repo: circleci-many-repo-sample

      - store_artifacts:
              path: ./build/libs
              destination: /artifacts

workflows:
  version: 2
  spa-and-java-build:
    jobs:
      - build-front
      - build:
          requires:
            - build-front

